Update syntax-test.yaml

diff --git a/.github/workflows/syntax-test.yaml b/.github/workflows/syntax-test.yaml
--- a/.github/workflows/syntax-test.yaml
+++ b/.github/workflows/syntax-test.yaml
@@ -1,131 +1,95 @@
-name: Release Images
+name: cli-release-build-native-linux
+
 on:
   workflow_dispatch: {}
   release:
     types: [released]
 
-
-# github.event context is only available when the workflow gets triggered by a release event. Therefore, commenting the below
-# section and add an additional step of fething the required details explicitly to make the workflow work with manual triggers
-
-#env:
-#  # Setting up workflow level environment varibles to make them available in both jobs
-#  # The values are extracted from the github.event context, which is automatically availble when a release a created.
-#  RELEASE_VERSION: ${{ github.event.release.name }}
-#  SOURCE_CODE_URL: ${{ github.event.release.zipball_url }}
-#  BRANCH: ${{ github.event.release.target_commitish }}
-
-
 jobs:
-  release-images:
+  build:
     if: github.repository_owner == 'Apicurio'
-    runs-on: ubuntu-18.04 
+    runs-on: ubuntu-latest
     steps:
-
-      - name: Fetch required Details
-        run: |
+    - name: Fetch required Details
+      run: |
           touch latestRelease.json && curl https://api.github.com/repos/apicurio/apicurio-registry/releases/latest > latestRelease.json
-          echo "RELEASE_VERSION=$(cat latestRelease.json | jq '.name' | sed 's/"//g')" >> $GITHUB_ENV
-          echo "SOURCE_CODE_URL=$(cat latestRelease.json | jq '.zipball_url' | sed 's/"//g')" >> $GITHUB_ENV
-          echo "BRANCH=$(cat latestRelease.json | jq '.target_commitish' | sed 's/"//g')" >> $GITHUB_ENV
+          echo "RELEASE_VERSION=$(cat latestRelease.json | jq -r '.name')" >> $GITHUB_ENV
+          echo "SOURCE_CODE_URL=$(cat latestRelease.json | jq -r '.zipball_url')" >> $GITHUB_ENV
+          echo "UPLOAD_URL=$(cat latestRelease.json | jq -r '.upload_url')" >> $GITHUB_ENV
+    
+    - name: Log Environment Variables
+      run: |
+        echo "$RELEASE_VERSION"
+        echo "$SOURCE_CODE_URL"
+        echo "$UPLOAD_URL"
 
-      - name: Download Source Code
-        run: wget -c $SOURCE_CODE_URL && unzip $RELEASE_VERSION && ls -lrt && mv ${{github.repository_owner}}* registry
+    - name: Download Source Code
+      run: wget -c $SOURCE_CODE_URL && unzip $RELEASE_VERSION && ls -lrt && mv ${{github.repository_owner}}* registry
         
-      # We have faced issues in the past where a github release was created from a wrong commit
-      # This step will ensure that the release was created from the right commit  
-      - name: Verify Project Version
-        run: |
-          cd registry
-          PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-          if [[ $PROJECT_VERSION != $RELEASE_VERSION ]]
-          then
-              echo "ERROR: Project Version '${PROJECT_VERSION}' does not match with Released Version '${RELEASE_VERSION}'"
-              exit 1	  
-          fi
+    - name: Verify Project Version
+      run: |
+        cd registry
+        PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+        if [[ $PROJECT_VERSION != $RELEASE_VERSION ]]
+        then
+            echo "ERROR: Project Version '${PROJECT_VERSION}' does not match with Released Version '${RELEASE_VERSION}'"
+            exit 1	  
+        fi
+        
+    - name: Install graalvm
+      uses: DeLaGuardo/setup-graalvm@4.0
+      with:
+        # GraalVM version, no pattern syntax available atm
+        graalvm: '21.0.0.2'
+        # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
+        java: 'java11'
+        # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
+        arch: 'amd64'
 
-      - name: Set up JDK 11
-        uses: AdoptOpenJDK/install-jdk@v1
-        with:
-          version: '11'
-          architecture: x64
+    - name: Install native-image
+      run: gu install native-image
 
-      - name: Build Project
-        run: cd registry && make SKIP_TESTS=true BUILD_FLAGS='-Dmaven.wagon.httpconnectionManager.maxTotal=30 -Dmaven.wagon.http.retryHandler.count=5' build-all
+    - name: Get maven wrapper
+      run: cd registry && mvn -N io.takari:maven:wrapper -Dmaven=3.6.3
 
-      - name: Build The Images For Docker.io
-        run: cd registry && ./.github/scripts/build-images.sh ${BRANCH} docker.io release ${RELEASE_VERSION} 
-
-      - name: List All Docker Images
-        run: docker images
+    - name: Build jvm jar
+      run: cd registry && ./mvnw -pl cli -am install
       
-      - name: Login to DockerHub Registry
-        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-          
-      - name: Push The Images To Docker.io 
-        run: cd registry && ./.github/scripts/push-images.sh ${BRANCH} docker.io release ${RELEASE_VERSION}
-        
-      - name: Build The Images For Quay.io
-        run: cd registry && ./.github/scripts/build-images.sh ${BRANCH} quay.io release ${RELEASE_VERSION}
+    - name: View Files
+      run: ls -lrt registry/cli/target/
 
-      - name: List All Docker Images
-        run: docker images
-          
-      - name: Login to Quay.io Registry
-        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" Quay.io
-          
-      - name: Push The Images To Quay.io 
-        run: cd registry && ./.github/scripts/push-images.sh ${BRANCH} quay.io release ${RELEASE_VERSION}
-          
-      - name: Push The Images To Quay.io 
-        run: cd registry && ./.github/scripts/push-images.sh ${BRANCH} quay.io release ${RELEASE_VERSION}
+    - name: Upload jvm jar
+      id: upload-jar
+      uses: actions/upload-release-asset@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ env.UPLOAD_URL }}
+        asset_path: ./registry/cli/target/apicurio-registry-cli-${{ env.RELEASE_VERSION }}-runner.jar
+        asset_name: apicurio-registry-cli-${{ env.RELEASE_VERSION }}.jar
+        asset_content_type: application/octet-stream
 
-      - name: Google Chat Notification
-        if: ${{ failure() }}
-        uses: Co-qn/google-chat-notification@releases/v1
-        with:
+    - name: Build native executable
+      run: cd registry && ./mvnw -pl cli package -Dnative
+    
+    - name: View Files
+      run: ls -lrt registry/cli/target/
+      
+    - name: Upload native executable
+      id: upload-native-executable
+      uses: actions/upload-release-asset@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ env.UPLOAD_URL }}
+        asset_path: ./registry/cli/target/apicurio-registry-cli-${{ env.RELEASE_VERSION }}-runner
+        asset_name: apicurio-registry-cli-${{ env.RELEASE_VERSION }}-linux
+        asset_content_type: application/octet-stream
+
+    - name: Google Chat Notification
+      if: ${{ failure() }}
+      uses: Co-qn/google-chat-notification@releases/v1
+      with:
           name: ${{ github.workflow }}
           url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
           status: ${{ job.status }}
-
-  verify-release:
-    runs-on: ubuntu-18.04
-    needs: ["release-images"]   # The Job gets triggered only after the "release-images" job has successfully completed. The job doesn't run in case the "release-images" job fails
-    if: github.repository_owner == 'Apicurio'
-    steps:
-
-      - name: Fetch required Details
-        run: |
-          touch latestRelease.json && curl https://api.github.com/repos/apicurio/apicurio-registry/releases/latest > latestRelease.json
-          echo "RELEASE_VERSION=$(cat latestRelease.json | jq '.name' | sed 's/"//g')" >> $GITHUB_ENV
-          echo "SOURCE_CODE_URL=$(cat latestRelease.json | jq '.zipball_url' | sed 's/"//g')" >> $GITHUB_ENV
-          echo "BRANCH=$(cat latestRelease.json | jq '.target_commitish' | sed 's/"//g')" >> $GITHUB_ENV
-
-      - name: Checkout Code with Ref '${{ github.ref }}'
-        uses: actions/checkout@v2      
-
-      - name: Determine Floating Tag
-        run: |
-          if [[ $BRANCH == 'master' ]]
-          then
-              echo "FLOATING_TAG=latest-release" >> $GITHUB_ENV
-          else
-              echo "FLOATING_TAG=$BRANCH-release" >> $GITHUB_ENV
-          fi
-
-      - name: Verify Docker Release For mem
-        run: cd apicurio-registry && ./.github/scripts/verify-docker-release.sh apicurio/apicurio-registry-mem:${RELEASE_VERSION} apicurio/apicurio-registry-mem:${FLOATING_TAG} 
-     
-      - name: Verify Docker Release For sql
-        run: cd apicurio-registry && ./.github/scripts/verify-docker-release.sh apicurio/apicurio-registry-sql:${RELEASE_VERSION} apicurio/apicurio-registry-sql:${FLOATING_TAG}  
-    
-      - name: Verify Docker Release For kafkasql
-        run: cd apicurio-registry && ./.github/scripts/verify-docker-release.sh apicurio/apicurio-registry-kafkasql:${RELEASE_VERSION} apicurio/apicurio-registry-kafkasql:${FLOATING_TAG}
-
-      - name: Google Chat Notification
-        if: ${{ failure() }}
-        uses: Co-qn/google-chat-notification@releases/v1
-        with:
-          name: ${{ github.workflow }}
-          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
-          status: ${{ job.status }}  
